GRAVITY = 3
COE = 0.3
VELOCITY_RESOLVER_MAX_ITERATIONS = 100
CONTACT_RESOLVER_MAX_ITERATIONS = 100
SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 800
EPS = 1E-5

RESTING_CONTACT_THRES = 50 # number of iterations before we mark contact as resting
DELTA = 2**2 # 
DELTA_THETA = 0.01
